name: Build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: set versions
        run: |
          echo "VERSION_NAUTOBOT=$(cat VERSION_NAUTOBOT)" >> $GITHUB_ENV
          echo "VERSION_CONTAINER=$(cat VERSION_NAUTOBOT)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up QEMU for arm64 support
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/sirtux/nautobot-docker:${{ env.VERSION_CONTAINER }}
          build-args: |
            VERSION_NAUTOBOT=${{ env.VERSION_NAUTOBOT }}

